Fixed exception handling, updated dependencies.
utily/cloudly-router pull request #25
Opened 2023-06-14 09:34 UTC by AntonCroner

2023-06-14 16:08 UTC, simonmika requested changes
Fix the real error instead of introducing new faults. Ask for help if needed.

2023-06-14 16:08 UTC, simonmika commented on Router.ts
> +		readonly catch: boolean | ((exception: unknown) => http.Response)
No, we don't want this change.

2023-06-14 16:08 UTC, simonmika commented on Router.ts
> +						  }
We explicitly want the error message to be a JSON compatible with a gracely error.

2023-06-19 17:03 UTC, AntonCroner commented on Router.ts
> +						  }
Reverted.

2023-06-19 17:03 UTC, AntonCroner commented on Router.ts
> +						  }
Reverted.

2023-09-29 14:46 UTC, closed without merging