handle can take context factory
utily/cloudly-router pull request #37
Opened 2023-10-11 12:52 UTC by EliasEriksson

* `Router.handle(...)` can be called with a context factory function.

2023-10-12 07:14 UTC, simonmika requested changes

2023-10-12 07:14 UTC, simonmika commented on Router.ts
> +
In what way does the type of factory/context influence the types of the rest? If not just call it context and overload the type and get rid of all the new overloads.

2023-10-16 07:12 UTC, EliasEriksson commented on Router.ts
> +
not sure why I did not do that from the start.

2023-10-18 07:57 UTC, simonmika approved these changes

2023-10-18 07:57 UTC, merged